/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

declare const self: ServiceWorkerGlobalScope;

// Take control immediately
self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// Push notification handler
self.addEventListener('push', (event: PushEvent) => {
  const data = event.data?.json() as {
    title: string;
    body: string;
    alertId?: string;
  } | null;

  if (!data) return;

  event.waitUntil(
    self.registration.showNotification(data.title, {
      body: data.body,
      icon: '/icons/icon-192.png',
      badge: '/icons/icon-192.png',
      tag: data.alertId ?? 'catchit-alert',
      requireInteraction: true,
      data: { url: '/alerts' },
    })
  );
});

// Handle notification click — open the app
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close();
  const targetUrl = (event.notification.data?.url as string) || '/';

  event.waitUntil(
    (self.clients as Clients).matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if (client.url.includes(targetUrl) && 'focus' in client) {
          return (client as WindowClient).focus();
        }
      }
      return (self.clients as Clients).openWindow(targetUrl);
    })
  );
});
